### PR TITLE
Fix some shit

### LINKED ISSUE #177: [BUG] [0.9.1] Systems that provide quick or full actions that are not distinctly named default to "New Action"
**Describe the bug**
Under the new system you have for allowing quick, full and protocol actions to be taken directly from mech systems, systems that provide quick or full actions that do not have names distinct from the system that provide them usually have the action listed as "New Action."

I have made an attempt to list all the systems that have this issue, but please note that this _may_ not be exhaustive:
Accelerate
Aceso Stabilizer
Active Camouflage
Antilinear Time
Argonaut Shield
Auto-Cooler
Blinkshield
Blinkspace Tunneler
Cable Winch System
Caltrop Launcher
Charged Stake
Core Siphon
EMP Pulse
Enclave-Pattern Support Shield
External Ammo Feed
Eye of Horus
Fade Cloak
Ferrous Lash
Field-Approved, Brass-Ignorant Modifications
Final Secret
Flak Launcher
Forge Clamps
Hardlight Defense System
Hunter Lock
Hyperdense Armor
Interdiction Field
Javelin Rockets
LB/OC Cloaking Field
Lightning Generator
Magnetic Shield
Markerlight
Metahook
Monitor Module
Oasis Wall
PEBCAC
Plasma Gauntlet
RAMJET
Realspace Breach
Redundant Systems Upgrade
Repulser Field
Retractable PRofile
Seismic Ripper
Siege Stabilizers
Spaceborn EVA
Stasis Generator
Stay of Execution
Stuncrown
Swarm Body
Total Strength Suite I
Total Strength Suite II
Total Strength Suite III
Tracking Bug
Whitewash Sealant Spray

**To Reproduce**
1. Install one of the above listed systems
2. Note the name of the action that it allows you to take

**Expected behavior**
Honestly I'm not quite sure, but I would presume that in lieu of any other option, the name of the action should default to the name of the system?

**Screenshots**
New Action

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.1.20

**Discord contact info**
Vex#1075

### LINKED ISSUE #184: [BUG] [0.9.1] Superheavy weapons produce "weapon too large" error even in heavy mount
**Describe the bug**
When a Superheavy weapon is placed in a Heavy mount, even if there is an unoccupied main mount available on the mech, the mech will display an error stating "WEAPON TOO LARGE TO FIT."

**To Reproduce**
1. Create a mech with the weapon mounts necessary to correctly equip a Superheavy Weapon (e.g. Everest, Tortuga, etc.)
2. Mount a superheavy weapon to the Heavy Mount, while leaving the Main mount free.

**Expected behavior**
I realise there probably isn't an automated function yet to make Superheavy weapons automatically occupy a Main Mount, or at least check if there's an unoccupied Main Mount, but this should be addressed at some point.

**Screenshots**
Superheavy Weapons

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.7.9
 - Lancer system version 0.9.1

**Discord contact info**
Vex#1075

### LINKED ISSUE #201: [BUG][9.2] Improved Armament is not factored into the character sheet.
**Describe the bug**
Character has IMPROVED ARMAMENT core bonus but Comp/Con does not import that mount/weapons over to the character sheet.

**To Reproduce**
1: Create a pilot with Improved Armament Core Bonus
2: Add a weapon mount to the Improved Armament mount in C/C.
3: Sync pilot.

**Expected behavior**
Improved Armament would show up on the character sheet for the mech.

**Screenshots**
You may utilize 80a2bc45d3374ff8d63b9e77fe0831b8 share code to check on 9.2

**Platform (please complete the following information):**
 - Current Foundry build 0.7.9
 - Windows 10, latest updates.
 - 9.2

**Additional context**
It can be built manually using the sheet, so it's not outright required, unsure if it's a bug or just not supported, but seems like a bug.

**Discord contact info**
Wakefield#2890

### LINKED ISSUE #234: [BUG] NPC Notes not saving edits
**Describe the bug**
Whenever I try to add a note to a NPC character sheet, it won't save to the sheet. 

**To Reproduce**
1. Create a NPC actor sheet.
2. Scroll down to the 'Notes' Section
3. Click on the 'edit' button
4. Write anything on the edit field.
5. Click on either 'save' buttons
4. See error on the character sheet.

**Expected behavior**
When I edit the note on the NPC character sheet, I expect it to reflect on the sheet, and be editable afterwards.

**Screenshots**
image
image
image

**Platform (please complete the following information):**
 - OS: MacOS X 11.4 (Big Sur)
 - Browser: Chrome 91.0.4472.114
 - Foundry version: v0.8.6 (tested on v0.8.7)
 - Lancer system version: v0.9.4

**Additional context**
Disabled all the mods and the behavior was the same. Running server on the Forge server hosting.
The Notes Section of the player actor sheet is working propperly, though.

**Discord contact info**
alkyama#2737

### LINKED ISSUE #235: [BUG] Empty Status and Conditions Compendium
**Describe the bug**
_Status/Conditions_ Compendium has empty entries.

**To Reproduce**
1. Open 'Status/Conditions' Compendium
2. Click on any Compendium Entry
3. See the Error

**Expected behavior**
When I open the condition/status entry, I expect to see a description of the condition, like on Comp/Con.

**Screenshots**
image

**Platform (please complete the following information):**
 - OS: MacOS 11.4 (Big Sur)
 - Browser: Chrome 91.0.4472.114 
 - Foundry version: v0.8.7
 - Lancer system version v0.9.4

**Additional context**
N/A

**Discord contact info**
alkyama#2737

### LINKED ISSUE #236: [BUG] Can't open Talent Compendium Entries
**Describe the bug**
Whenever I try to open Talent Compendium entries, they won't open any modals, with the console reporting the error recorded on the screenshot below.

**To Reproduce**
1. Go to 'Compendiums' Section
2. Open the 'Talent' Compendium List
3. Click on 'Ace' Compendium Entry

**Expected behavior**
When I click on the talent compendium entry, I want it to open so I can read it.

**Screenshots**
image

**Platform (please complete the following information):**
- OS: MacOS 11.4 (Big Sur)
- Browser: Chrome 91.0.4472.114
- Foundry version: v0.8.7
- Lancer system version v0.9.4

**Additional context**
Because of this, I cannot create the sheets with talents beyond the first tier of the talent without the aid of Comp/Con. The talents pulled directly from the compendium list will always create the first tier, even duplicating the existing entry.

**Discord contact info**
alkyama#2737

### PR DESCRIPTION
**Pull request by whitespine**
Fixes #235 
Fixes #236 
Fixes #234 
Fixes #177 
Sorta kinda fixes #201, maybe
Provides infratructure to fix #184. Mounts need to be made able to be marked as superheavy bracing.

### CODE REVIEW

**Comment by whitespine** [comment]
Oh i forgot to mention, you can sort npc features now

**Comment by whitespine** [comment]
Also fixes #174, #243. #184

**Comment by whitespine** [comment]
Resolves #176  (this was done earlier, forgot)
Ready to go imo

**Comment by Grygon** [comment]
Integrated mount is bracing... something 
image

**Comment by whitespine** [comment]
There's no actual flag for what bracing is - I guess `lock` serves a dual purpose :/ . Will fix

**Review by Grygon — APPROVED** [review]

**Pull request merged**
