### PR TITLE
Improve Scan (Journal) macro to not rely on names.

### PR DESCRIPTION
**Pull request by Akaito**
- Improve macro to make use of flags. When a new scan JournalEntry is created, store that entry's ID in the target's flags.  When scanning, try to find a JournalEntry with the matching ID.  Far faster, and prevents tokens with the same name from overwriting each other's scan journal entries.  If there is no stored flag, fallback to doing name-comparison on the JournalEntries.  This can be improved later, but the change was kept smaller for now. Failing that, create a new JournalEntry.
- Replace use of regex-matching name search with simple string-inside compare. Faster.  Doesn't break with parenthesis or other regex characters in names.

### CODE REVIEW

**Comment by Akaito** [comment]
If there's a not-painful way to update macros or other items in .db files, please do let me know.  This ended up being pretty annoying.  And the diff is nearly impossible to read.  Here's the macro source in a more human-friendly format:
```javascript
//Sanity Check - Can this user even create folders and journal entries? Does the folder journal folder exist?
if (JournalEntry.canUserCreate(game.user) == false) {
  ui.notifications.error(`${game.user.name} attempted to run SCAN to Journal but lacks proper permissions. Please correct and try again.`);
  return;
};

//Variables - Change these to control the macro

//journalFolderName - The name, as displayed in foundry, of the folder you want the journal entries to save to. Remember to enclose in quotes: 'example'
const journalFolderName = 'SCAN Database';

//nameTemplate - The text before the scan number and target name. Remember to enclose in quotes: 'example'
const nameTemplate = 'SCAN: ';

//numberLength - The total length of the scan number, extra spaces are filled with 0s. Setting this to 3, for example would produce scan number 001 on your first scan. Integers only and no quotes.
const numberLength = 3;

//startingNumber - If you want the scan number to start at something other than 1 then change this. Integers only and no quotes.
const startingNumber = 1;

//permissionLevel - This sets the default permission level of the scan entry. Suggested options are NONE, LIMITED, OBSERVER, or OWNER.
const permissionLevel = CONST.DOCUMENT_PERMISSION_LEVELS.OWNER;

//updateExisting - This macro will check if a scan journal entry exists and update it, set this to false if you want it to create a new scan journal entry.
const updateExisting = true;

//targets - Gets the data for your currently selected target(s) and stores it for later use. Do not change.
let targets = Array.from(game.user.targets);

//Functions
//zeroPad - Adds a set number 0s to the fed number to produce a consistent length number.
const zeroPad = (num, places) => String(num).padStart(places, '0');

//sort_features - Sorts the feature list for the scanned target    
function sort_features(a, b) {
  return b.Origin.base - a.Origin.base
};

//construct_features - Builds out the list of selectable features for the scanned target, includes support for exotics.
function construct_features(sc_dir, o) {
  let sc_list = ``;
  sc_list += `<p>${o}</p>`
  let sc_features = sc_dir._features.filter(f => f.Origin.name == o).sort(sort_features)
  sc_features.forEach(i => {
    let sc_name = ``;
    let sc_desc = ``;
    if (i.Origin.name == "EXOTIC" && !i.Origin.base) {
      sc_name = "<code class=\"horus--subtle\">UNKNOWN EXOTIC SYSTEM</code>";
      sc_desc = "???";
    }
    else {
      sc_name = i.Name;
      if (i.Effect) {
        sc_desc = i.Effect;
      } else {
        sc_desc = "No description given.";
      }
      if (i.Trigger) {
        sc_desc = `Trigger:${i.Trigger}<br>${sc_desc}`;
      }
    }
    let sc_entry = `<details><summary>${sc_name}</summary><p>${sc_desc}</p></details>`;
    sc_list += sc_entry;
  });
  return sc_list
};

//construct_weapons - Builds out the table of weapons for the scanned target, includes support for exotics.
function construct_weapons(sc_dir, o, sc_tier) {
  let sc_weapons = ``;
  let sc_features = sc_dir._features.filter(f => f.Origin.name == o).sort(sort_features)
  sc_features.forEach(i => {
    let sc_name = ``;
    let sc_desc = ``;
    let sc_entry = ``;
    let sc_range = ``;
    let sc_damage = ``;
    let sc_accuracy = ``;
    if (!i.WepType) { return sc_weapons };
    sc_weapons += `<table>`;
    if (i.Origin.name == "EXOTIC" && !i.Origin.base) {
      sc_name = "<tr><th><code class=\"horus--subtle\">UNKNOWN EXOTIC WEAPON</code></th></tr>";
      sc_desc = "<tr><td>???</td></tr>";
      sc_entry = sc_name + sc_desc;
    }
    else {
      sc_name = `<tr><th colspan="4">${i.Name}</th></tr>`;
      sc_entry += sc_name;
      sc_desc = `<tr>`;
      sc_desc += `<td>+${i.AttackBonus[sc_tier - 1]} ATTACK</td>`;
      if (i.Accuracy[sc_tier - 1]) {
        if (i.Accuracy[sc_tier - 1] > 0) {
          sc_accuracy = '+' + i.Accuracy[sc_tier - 1] + ' ACCURACY'
        } else {
          sc_accuracy = '-' + i.Accuracy[sc_tier - 1] + ' DIFFICULTY'
        };
      };
      sc_desc += `<td>${sc_accuracy}</td>`;
      if (i.Range.length > 0) { i.Range.forEach(r => sc_range += r.RangeType + ' ' + r.Value + '&nbsp&nbsp&nbsp') };
      sc_desc += `<td>${sc_range}</td>`;
      if (i.Damage.length > 0) { i.Damage[sc_tier - 1].forEach(d => sc_damage += d.Value + ' ' + d.DamageType + '&nbsp&nbsp&nbsp') };
      sc_desc += `<td>${sc_damage}</td>`;
      if (i.Loaded) { sc_desc += `<td>LOADED</td>` } else { sc_desc += `<td>UNLOADED</td>` };
      if (i.Uses > 0 && i.BaseLimit > 0) { sc_desc += `<td>USES: ${i.Uses}/${i.BaseLimit}</td>` };
      sc_desc += `<tr>`;
      if (i.Trigger) {
        sc_desc += `<tr><td colspan="6"><details><summary>Trigger</summary><p>${i.Trigger}</p></details></td></tr>`;
      };
      if (i.OnHit) {
        sc_desc += `<tr><td colspan="6"><details><summary>On Hit</summary><p>${i.OnHit}</p></details></td></tr>`;
      };
      if (i.Effect) {
        sc_desc += `<tr><td colspan="6">${i.Effect}</td></tr>`;
      };
      if (i.Tags.length > 0) {
        sc_desc += `<tr><td colspan="6"><details><summary>Tags</summary>`;
        i.Tags.forEach((t, index) => {
          sc_desc += `<p>${t.Tag.Name.replace("{VAL}", t.Value)}</p>`;
        });
        sc_desc += `</details></td></tr>`;
      };
      sc_entry += sc_desc;
    }
    sc_weapons += sc_entry;
    sc_weapons += `</table>`
  });
  return sc_weapons
};

//construct_templates
function construct_templates(sc_dir) {
  let sc_templates = ``;
  let sc_temp = sc_dir._templates;
  if (!sc_temp || sc_temp.length == 0) {
    sc_templates += "<p>NONE</p>";
  } else {
    sc_temp.forEach(i => {
      let sc_entry = `<p>${i.Name}</p>`;
      sc_templates += sc_entry;
    });
  }

  sc_templates += "<br>";
  return sc_templates
};

const journalFolder = game.folders.getName(journalFolderName)
if (!journalFolder && journalFolderName.length > 0) {
  try {
    await Folder.create({ name: journalFolderName, type: "JournalEntry" })
  } catch (error) {
    ui.notifications.error(`${journalFolderName} does not exist and must be created manually by a user with permissions to do so.`);
    return;
  }
};

targets.forEach(async (target, index) => {
  let sc_dir = await target.document.actor.system.derived.mm_promise;
  let hase_table_html = `
    <p><img style="border: 3px dashed #000000; float: left; margin-right: 5px; margin-left: 5px;" src="${target.document.actor.img}" width="30%" height="30%" /></p>
    <div style="color: #000000; width: 65%; float: right; text-align: left;">
    <table>
        <tr>
            <th>HULL</th><th>AGI</th><th>SYS</th><th>ENG</th>
        </tr>
        <tr>
            <td>${sc_dir.Hull || 0}</td><td>${sc_dir.Agi || 0}</td><td>${sc_dir.Sys || 0}</td><td>${sc_dir.Eng || 0}</td>
        </tr>
    </table>
    `
  let stat_table_html = `
    <table>
        <tr>
            <th>Armor</th><th>HP</th><th>Heat</th><th>Speed</th>
        </tr>
        <tr>
            <td>${sc_dir.Armor}</td><td>${sc_dir.CurrentHP}/${sc_dir.MaxHP}</td><td>${sc_dir.CurrentHeat || 0}/${sc_dir.HeatCapacity || 0}</td><td>${sc_dir.Speed}</td>
        </tr>
        <tr>
            <th>Evasion</th><th>E-Def</th><th>Save</th><th>Sensors</th>
        </tr>
        <tr>
            <td>${sc_dir.Evasion}</td><td>${sc_dir.EDefense}</td><td>${sc_dir.SaveTarget}</td><td>${sc_dir.SensorRange}</td>
        </tr>
        <tr>
            <th>Size</th><th>Activ</th><th>Struct</th><th>Stress</th>
        </tr>
        <tr>
            <td>${sc_dir.Size}</td><td>${sc_dir.Activations || 1}</td><td>${sc_dir.CurrentStructure || 0}/${sc_dir.MaxStructure || 0}</td><td>${sc_dir.CurrentStress || 0}/${sc_dir.MaxStress || 0}</td>
        </tr>
    </table>
    `
  console.log('sc_dir:', sc_dir);
  let sc_class = (!sc_dir._classes || sc_dir._classes.length == 0) ? "NONE" : sc_dir._classes[0].Name
  let sc_tier = sc_dir.Tier ? sc_dir.Tier : 0
  let sc_templates = construct_templates(sc_dir)
  let sc_list = ``
  let sc_weapons = ``
  if (!sc_dir._features || sc_dir._features.length == 0) {
    sc_list += "<p>NONE</p>";
    sc_weapons += "<p>NONE</p>";
  } else {
    let sc_origins = new Array;
    sc_dir._features.forEach(f => {
      let origin = f.Origin.name;
      if (!sc_origins.includes(origin)) {
        sc_origins.push(origin);
      };
    });
    sc_origins.forEach(o => {
      sc_list += construct_features(sc_dir, o);
      sc_weapons += construct_weapons(sc_dir, o, sc_tier);
    });
  };

  /*
  ChatMessage.create({
      user: game.user._id,
      content: `<h2>Scan results: ${sc_dir.Name}</h2>` + `<h3>Class: ${sc_class}, Tier ${sc_tier}</h3>`  + hase_table_html + stat_table_html + `<h3>Templates:</h3>` + sc_templates + `<h3>Systems:</h3>` + sc_list
  });
  */

  var scanContent = `<h2>Scan results: ${sc_dir.Name}</h2>` + `<h3>Class: ${sc_class}, Tier ${sc_tier}</h3>` + hase_table_html + stat_table_html + `</div><div style="color: #000000; width: 100%; float: right; text-align: left;"><h3>Weapons:</h3>` + sc_weapons + `<h3>Templates:</h3>` + sc_templates + `<h3>Systems:</h3>` + sc_list + `</div>`

  //This checks and updates the scan entry for the target(s) if a single scan entry exists in the specified folder for the target(s) along with the updateExisting flag.
  //If either are false then this creates a new scan entry.

  let rootScanFolder = journalFolderName ? journalFolder : game.journal;
  let scanFolderId = journalFolderName ? journalFolder.id : null;
  let scanObj = new Object();
  scanObj.folder = scanFolderId;
  
  let matchingJournalEntries;
  // First try the quick thing of getting a journal by its ID.
  // Taking the journal ID from the flag this macro previously stored.
  let scanMacroJournalId = target.document?.flags?.lancer_scan_macro?.journal_id;
  if (scanMacroJournalId) {
    console.log("discovered stored SCAN journal ID in target's flags", scanMacroJournalId, game.journal.get(scanMacroJournalId));
    matchingJournalEntries = [game.journal.get(scanMacroJournalId)];
    console.log('journal-get result:', matchingJournalEntries);
  }
  // Or, fallback to regex-searching.  Note names with parentheses will fail this type of search.
  else {
    console.log('searching for matches', journalFolderName, journalFolder, game.journal, journalFolder.id);
    // old regex way, which fails when parens or other regex special characters are involved
    //matchingJournalEntries = rootScanFolder.contents.filter(e => e.name.match(sc_dir.Name));
    // newer, faster, simpler plain string search
    matchingJournalEntries = rootScanFolder.contents.filter(e => e.name.includes(sc_dir.Name));
  }
  
  let scanEntry;
  if (matchingJournalEntries.length == 1 && updateExisting === true) {
    console.log("Updating an existing scan")
    scanObj.name = matchingJournalEntries[0].name;
    scanObj._id = matchingJournalEntries[0]._id;
    scanObj.text = new Object();
    scanObj.text.content = scanContent;
    scanEntry = game.journal.getName(scanObj.name);
    let scanPage = scanEntry.pages.getName(scanObj.name)
    await scanPage.update(scanObj);
  } else {
    console.log("Creating a new scan")
    let scanCount = zeroPad(rootScanFolder.contents.filter(e => e.name.startsWith(nameTemplate)).length + startingNumber, numberLength);
    scanObj.name = nameTemplate + scanCount + ` - ` + sc_dir.Name;
    scanObj.content = scanContent;
    scanEntry = await JournalEntry.create(scanObj);
    // Store ID of scan's journal entry on the token's document, for later lookup.
    await target.document.update({flags: {lancer_scan_macro: {journal_id: scanEntry.id}}});
  };

  scanEntry.update({ permission: { default: permissionLevel } });
  scanEntry.sheet.render(true);

})
```

**Comment by msprijatelj** [comment]
Can you clarify the algorithmic flow for the case below?

1. Two unlinked NPC tokens (call them Token 1 and Token 2) with the same source actor (call it Actor) are created.
2. This macro scans Token 1. A journal entry is created. 
    - Does the Journal use Token 1’s name or Actor’s name? 
    - Does the flag get set on Token 1 or the Actor?
3. The macro then scans Token 2. 
    - Does it find a flag on Token 2? 
    - If not, does the name of Token 2 match the Journal entry of Token 1/Actor?
    - If it cannot find the flag nor the name of the Journal entry, does it then create a brand new Journal entry with duplicate information?

My main concern is that absolute last point: Will scanning multiple unlinked tokens with the same source actor make multiple Journal entries? (I’d personally prefer it simply update the entry, if only to prevent clutter.)

**Comment by Akaito** [comment]
Two tokens from the same actor will create different entries.  I'd done that intentionally so the stats of one wouldn't overwrite the scan of the other.  Especially for cases like scanning two tokens from the same actor at the same time.  Where you'd just lose one of the results.  (I'm not sure how often that actually happens in practice in Lancer play.)

I could rework this to have a preference at the top for whether or not the flag is used.  And when it's not, let this fallback to the .includes() string comparison (still instead of the prior regex .match() search).

What's the best way to get this kind of change into a PR, anyway?  For this, I imported the macro, made changes, edited the one in the .db, copied the .db down to my desktop, and manually edited the .db file in a diff/merge tool to ensure this was the only thing changing.  But that doesn't seem likely to be the best way.

**Comment by Eranziel** [comment]
I agree with Valk, creating separate journals for two unlinked tokens from the same actor seems unnecessary. If they're getting scanned often enough that the realtime hp is that relevant, I'd recommend using the other scan macro that prints to chat. I think the only time that multiple similar NPCs would get scanned at the same time would be Chomolungma's core, which IMHO is rare enough that the player & GM can be expected to do a little manual handling.

That said, I'm not really taking PRs to master anymore, until after v2.0 is released. There's just too much difference between master and the 2.0 branch.

Feel free to bring your changes into a branch based on `2.0-rc` if you like. On that branch, the compendiums are built from YAML files in https://github.com/Eranziel/foundryvtt-lancer/tree/2.0-rc/src/packs/core_macros, which makes them far more readable in an editor or PR.

**Comment by BoltsJ** [comment]
Hi! 2.0 is out now and we have a guide for contributing macros if you're feeling willing to update this for the new version.

https://github.com/Eranziel/foundryvtt-lancer/blob/master/docs/macro_guide.md

**Comment by BoltsJ** [comment]
Closing this as stale, but feel free to update and re-open or recreate it if you still want this change.

**Pull request closed without merging**
